### PR TITLE
Fix some addresses and geocodes detected by distance validation again…

### PR DESCRIPTION
**Pull request by jlgoldman**
…st offices from https://github.com/jlgoldman/membersofcongress

### CODE REVIEW

**Comment by jlgoldman** [comment]
As mentioned yesterday, I think something mangled a bunch of the addresses, resulting in junk like "1800 North" instead of "1800 5th Avenue North". After glancing at https://github.com/TheWalkers/congress-turk, my guess now is that it's the use of https://github.com/SwoopSearch/pyaddress within reconcile_detail_results.py.

I think that address parser needs to be thrown out since it's corrupting a bunch of addresses. I've caught many instances of this with my geocode validation script, but I'm worried there's still dozens of cases remaining. Do you have a before-and-after comparison that shows what the parser did to all the addresses?

**Comment by msimonborg** [comment]
I am geocoding each address too for a web API I'm working on that will serve this data, and also noticed that quite a few did not geocode. however I did not have the time to dig too deep into whether the addresses were wrong or just not geocoding for whatever reason, so I changed my geocoding input to city, state and zip only, just to get rough coordinates (which is good enough for my purposes). my application is most interested in phone numbers and connecting people to the closest office, so location by city serves the purpose well enough.

however, I do want all of the data to be 100% accurate, and I and many others I'm working with are willing to help any way we can. If @jlgoldman or the maintainers of this fork are interested in joining the Progressive Coders Network, where my project lives, to cross-collaborate on this, or to check out some other interesting OS projects, join here http://www.progcode.co/

there are over 500 members made up of developers of all skill levels, lawyers, activists, campaign officials, etc..., and a couple dozen active projects. and it's very easy to recruit help for your work, or to jump into someone else's project that interests you. I think it could make the task of maintaining this data less demanding

**Comment by tcarobruce** [comment]
Good catch -- it looks like pyaddress is not doing a job with streets with cardinal directions ("657 Second Avenue North", "100 First Street SW", etc).

Some sort of normalization is necessary to make the turk reconciliation process feasible, but maybe a different library would handle this better. Will follow up once I've had a chance to investigate further.

**Review by tcarobruce — APPROVED** [review]
These changes look good, thank you.

**Comment by jlgoldman** [comment]
@msimonborg Great, thanks for the pointer. I've signed up to join the Network. I'm interested in learning more about your project and seeing where we could collaborate.

**Pull request merged**
