### PR TITLE
Create congress_lookup.py

### PR DESCRIPTION
**Pull request by essandess**
Add the ability to look up specific fields by committee membership or member last name. Wildcards are used. For example,

```
./congress_lookup.py -c 'Financ*' fax
```

prints the fax numbers of all members of the **Senate Committee on Finance** and the **House Committee on Financial Services**.

The command

```
./congress_lookup.py -n Smith fax hours
```

prints all fax numbers and hours listed for any legislator named "Smith".

### CODE REVIEW

**Comment by TheWalkers** [comment]
Hi Steve:

This pull request should go against:

  https://github.com/unitedstates/congress-legislators

which is the parent of this fork.

**Comment by essandess** [comment]
@TheWalkers This PR is for your fork, not the parent.

I forked your fork because you have the necessary data file [legislators-district-offices.yaml](../../../TheWalkers/congress-legislators/blob/master/legislators-district-offices.yaml), which hasn't been pulled to the parent.

Would you please reopen and accept this PR?

As well as the lookup code, it contains a couple database additions.

**Comment by essandess** [comment]
Oh wait I see now. I didn't know I could do a PR off the parent's parent. I just issued another to [unitedstates/congress-legislators](../../../unitedstates/congress-legislators).

**Comment by TheWalkers** [comment]
Hey Steve:

The district office update would be very welcome, if you want to cherry pick that one.  If that's too much hassle, I can also just make the correction.

**Comment by essandess** [comment]
I believe that you'll still want to accept this PR to your fork because the [PR](https://github.com/unitedstates/congress-legislators/pull/405/files) I issued to your parent includes all the content you've added.

**Comment by essandess** [comment]
Uh, isolating those edits in a single PR is beyond my git fu. You'd better just add them by hand.

**Comment by TheWalkers** [comment]
Cool, will do.

**Pull request closed without merging**
